# Generated by Django 5.1.4 on 2024-12-07 06:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='date_marked',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='present',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Absent', max_length=10)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.attendee')),
            ],
        ),
    ]
